[package]
name = "slopos-sched"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"
crate-type = ["rlib"]

[dependencies]
slopos-boot = { path = "../boot" }
slopos-drivers = { path = "../drivers" }
slopos-lib = { path = "../lib" }
slopos-mm = { path = "../mm" }
spin.workspace = true

