[workspace]
members = ["graphics", "bindings"]
resolver = "3"

[workspace.dependencies]
cbindgen = "0.27"
bindgen = "0.72"
bindings = { path = "bindings" }

[profile.dev]
panic = "abort"
opt-level = 2

[profile.release]
panic = "abort"
opt-level = 2
lto = true
codegen-units = 1
