[package]
name = "slopos-userland"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"
crate-type = ["rlib"]

[dependencies]
slopos-drivers = { path = "../drivers" }
slopos-video = { path = "../video" }
slopos-boot = { path = "../boot" }
slopos-lib = { path = "../lib" }
slopos-sched = { path = "../sched" }

